sudo: false
language: python
addons:
    apt:
        sources:
            - deadsnakes
        packages:
            - python3.5
            - python3.5-dev
env:
    - TOXENV=py27-1.8
    - TOXENV=py27-1.9
    - TOXENV=py27-1.10
    - TOXENV=py34-1.8
    - TOXENV=py34-1.9
    - TOXENV=py34-1.10
    - TOXENV=py35-1.9
    - TOXENV=py35-1.10
install:
    - pip install tox
script:
    - export PYTHONPATH=$PYTHONPATH:`pwd`
    - tox
